# Generated by Django 2.1.1 on 2018-10-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180914_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_pictures/'),
        ),
    ]
