# Generated by Django 2.1.1 on 2018-10-10 05:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181009_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='empty.png', upload_to=users.models._get_upload_path),
        ),
    ]
