# Generated by Django 2.1.1 on 2018-09-17 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20180914_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('posted_on', models.DateTimeField(default=datetime.datetime(2018, 9, 17, 6, 29, 18, 745001, tzinfo=utc))),
                ('last_modified_on', models.DateTimeField(default=datetime.datetime(2018, 9, 17, 6, 29, 18, 745030, tzinfo=utc))),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
